### ISSUE TITLE
세팅에서 음소거 버튼 반대로 하기

### ISSUE THREAD

**Issue by nairoon** [NazLab/MatchCard#30]
현재는 이미지가 음소거라는 기준하에 on일 때 음소거 되는데
반대로 바꿔서 off 일때 음소거가 되고, 이미지 파일도 같이 변하게 할 것.

**Comment by syihpe** [comment]
해당이슈 진행상황 확인 요청

**Comment by nairoon** [comment]
이미지 파일 교체와 토글간의 연동 작업만 남음
