### ISSUE TITLE
[개선사항] 타임바 이미지 로직 변경

### ISSUE THREAD

**Issue by nairoon** [NazLab/MatchCard#46]
현재는 fillamount를 이용하여 줄이고 있는데, 이렇게 하면 단면이 보임.
단면이 보이지 않게, 슬라이드를 이용하여 크기로 줄이게 로직 변경

**Comment by syihpe** [comment]
회의결과 fill amount로 해도 문제 없을듯 함 
확인 후 이슈 Close 예정

**Comment by syihpe** [comment]
일단 이슈 클로즈 하겠음
